name: 'Failures summary and output brew bottle result'
description: 'Failures summary and output brew bottle result'

runs:
  using: "composite"
  steps:
    - name: "Failures summary"
      run: |
        touch bottles/steps_output.txt
        cat bottles/steps_output.txt
        rm bottles/steps_output.txt

    - name: "Brew bottle result"
      run: |
        cat bottles/bottle_output.txt
        rm bottles/bottle_output.txt