name: 'Failures summary and output brew bottle result'
description: 'Failures summary and output brew bottle result'

runs:
  using: "composite"
  steps:
    - name: "list on home"
      run: ls -al / || true
      shell: bash

    - name: "list on home github"
      run: ls -al /github || true
      shell: bash

    - name: "list on home"
      run: ls -al /github/home || true
      shell: bash

    - name: "Where am I"
      run: pwd || true
      shell: bash

    - name: "List of dir"
      run: ls -al || true
      shell: bash
      
    - name: "Where am I on bottles"
      run: ls -al bottles || true
      shell: bash
    
    - name: "Where am I on bottles"
      run: whoami
      shell: bash

    - name: "Change to github dir"
      run: cd ${{github.action_path}}
      shell: bash

    - name: "check new dir"
      run: pwd || true
      shell: bash

    - name: "list new dir"
      run: ls -al || true
      shell: bash

    - name: "get runner os"
      run: echo $RUNNER_OS
      shell: bash

    - name: "Failures summary"
      run: |
        touch bottles/steps_output.txt
        cat bottles/steps_output.txt
        rm bottles/steps_output.txt
      shell: bash

    - name: "Brew bottle result"
      run: |
        cat bottles/bottle_output.txt
        rm bottles/bottle_output.txt
      shell: bash
