name: 'Failures summary and output brew bottle result'
description: 'Failures summary and output brew bottle result'

runs:
  using: "composite"
  steps:
    - run: |
        cd ${{github.action_path}}
        touch bottles/steps_output.txt
        cat bottles/steps_output.txt
        rm bottles/steps_output.txt
      shell: bash

    - run: |
        cd ${{github.action_path}}
        cat bottles/bottle_output.txt
        rm bottles/bottle_output.txt
      shell: bash
